export enum Modules {
    Requirement = 'Requirement',
    Resource = 'Resource',
    Hiring = 'Hiring',
    Status = 'Status',
    History = 'History',
    Admin = 'admin',
    Location = 'Location',
    Resource_requirement = 'Resource requirement',
    Notification = 'Notification',
    Bench_resource = 'Bench Resource'
}

export enum Common {
    skip = 'skip',
    limit = 'limit',
    search = 'search',
    Delete = 'Delete',
    Discard = 'Discard',
    error_create = 'Error while creating a ',
    error_update = 'Error while updating a ',
    error_delete = 'Error while deleting a ',
    report = 'report',
    date = 'Date',
    month = 'Month',
    year = 'Year',
    empty_chart = 'No charts available.',
    bar = 'bar',
    hiring_chart = 'Hiring',
    mode = 'x',
    requirement_chart = 'Requirement',
    remainder_chart = 'Remainder',
    client_chart = 'Client',
    resource_requirement = 'Resource Requirement',
    resource_chart = 'Resource',
    hiring_stage = 'hiring_stage',
    hiring_status = 'hiring_status',
    stage = 'stage',
    status = 'status',
    password = 'password',
    confirmPassword = 'confirmPassword',
    edit = 'edit',
    text = 'text'
}

